provide a new method 'get' to get the current app json by 'app_id' …
teralytics/ansible-marathon-module pull request #7
Opened 2017-04-03 16:28 UTC by lhoss

…(provided as only param)

2017-04-03 17:45 UTC, vincepii requested changes

2017-04-03 17:45 UTC, vincepii commented on library/marathon.py
> +    elif state == 'get':
Please, also update the documentation at the top of the file about this state.

2017-04-04 09:53 UTC, Rudd-O approved these changes
Provided Vince's changes are performed, I am preemptively approving from my side.

2017-04-05 07:26 UTC, vincepii approved these changes

2017-04-05 07:27 UTC, merged